INFO     root:keyword_action.py:53 启动浏览器
INFO     root:keyword_action.py:114 打开测试地址:http://10.60.44.245:7170/newmbs
INFO     root:keyword_action.py:159 柜员：mindy登录成功！
INFO     root:Test57_NeiBuZiJinChi.py:41 开始测试内部资金池功能
DEBUG    root:Test57_NeiBuZiJinChi.py:7436 内部账户计息失败！Traceback (most recent call last):
  File "E:\ATS\ter_Oracle\Test57_NeiBuZiJinChi.py", line 7421, in test_trade
    implici_wait("xpath", "//span[contains(text(),'操作成功！')]")
  File "E:\ATS\Action\keyword_action.py", line 401, in implici_wait
    raise e
  File "E:\ATS\Action\keyword_action.py", line 399, in implici_wait
    getElement(driver, locator_method, locator_exp)
  File "E:\ATS\Action\find.py", line 14, in getElement
    raise err
  File "E:\ATS\Action\find.py", line 11, in getElement
    (lambda x: x.find_element(by=locationType, value = locatorExpression))
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "E:\ATS\Action\find.py", line 11, in <lambda>
    (lambda x: x.find_element(by=locationType, value = locatorExpression))
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=89.0.4389.114)